#!/usr/bin/env bash
# Script to transfer a file from a client to a remote server

# Check if exactly four parameters are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign variables to input arguments for readability
PATH_TO_FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Use scp to transfer the file to the user's home directory on the server
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"
